ALTER TABLE micro_apps ADD COLUMN status TEXT NOT NULL DEFAULT 'ONLINE';
ALTER TABLE menus ADD COLUMN status TEXT NOT NULL DEFAULT 'ONLINE';
ALTER TABLE registry_services ADD COLUMN status TEXT NOT NULL DEFAULT 'ONLINE';
