server {
    listen 80;
    server_name localhost;

    location /apps/demo-ui/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;
        add_header Content-Type application/javascript;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;
    }
}
