apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plantx.fullname" . }}-order-config
  labels:
    {{- include "plantx.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.orderService.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
