{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "plantx.name" . }}-postgres
  labels:
    {{- include "plantx.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  serviceName: {{ include "plantx.name" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "plantx.name" . }}-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "plantx.name" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgresql.auth.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgresql.auth.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgresql.auth.database }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "plantx.name" . }}-postgres
spec:
  selector:
    app.kubernetes.io/name: {{ include "plantx.name" . }}-postgres
  ports:
    - port: 5432
{{- end }}
