apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plantx.fullname" . }}-order-secrets
  labels:
    {{- include "plantx.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.orderService.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
