events {
    worker_connections 1024;
}

http {
    include /etc/nginx/conf.d/upstreams.conf;

    include /etc/nginx/conf.d/rate-limits.conf;
    limit_req_status 429;

    server {
        listen 80;

        include /etc/nginx/conf.d/locations.conf;
        include /etc/nginx/conf.d/micro-app-locations.conf;
        include /etc/nginx/conf.d/static-locations.conf;
    }
}
