events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;

    include /etc/nginx/conf.d/rate-limits.conf;
    limit_req_status 429;

    server {
        listen 80;

        include /etc/nginx/conf.d/locations.conf;
        include /etc/nginx/conf.d/micro-app-locations.conf;
        include /etc/nginx/conf.d/static-locations.conf;
    }
}
