server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Don't cache the SPA entry and micro-app HTML entries during development
    location ~* \.html$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        expires -1;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /apps/ {
        try_files $uri $uri/ =404;
    }

    location /openapi/ {
        try_files $uri $uri/ =404;
    }
}
